version: 1
id: openai
config:
  whitelist:
    - gpt-5.6-sol
    - gpt-5.6-sol-fast
    - gpt-5.6-terra
    - gpt-5.6-terra-fast
    - gpt-5.6-luna
    - gpt-5.6-luna-fast
  models:
    gpt-5.6-sol:
      limit:
        context: 872000
        input: 872000
        output: 128000
    gpt-5.6-terra:
      limit:
        context: 872000
        input: 872000
        output: 128000
    gpt-5.6-luna:
      limit:
        context: 872000
        input: 872000
        output: 128000
    gpt-5.6-sol-fast:
      limit:
        context: 872000
        input: 872000
        output: 128000
    gpt-5.6-terra-fast:
      limit:
        context: 872000
        input: 872000
        output: 128000
    gpt-5.6-luna-fast:
      limit:
        context: 872000
        input: 872000
        output: 128000