version: ENC[AES256_GCM,data:Fw==,iv:6cBmWQWkOZGuBz+gNgx9VW3XCem9+8mbDjKiL+9/aOk=,tag:y/ZR5EngVwrHy7NxATKo/g==,type:int]
secrets:
    routin-plan: ENC[AES256_GCM,data:YIoTZZMlOqsAHkMb4u5+3gydnmYZjN/3N4876ULPo09+aQcZog==,iv:7G/mh1W5eN4YrCSgNOLqqoc1zLae8dRwJqRnRkTuyKc=,tag:t/WjOZgxP7ipkDh7J+oBwA==,type:str]
    gmn: ENC[AES256_GCM,data:GJnrXSaA8mT0HVEDDvH5IN/YUMWz81NebMzTa5j+6NS5ps4Xn1D/agSrS+vzglB2VXbfJCgZJN7mFzAbjS3wCnLLbg==,iv:opv00/O/AVeV1zLmeTjlhpRdhdJJqwI+ivMUFp4gK9I=,tag:8Sd6oht3d2GbfTtO9I3E0Q==,type:str]
    yybb: ENC[AES256_GCM,data:YO2BXHDtDCD/Nof6pY2Ru2jYtKGqes/BgT9hYDJ0wkrpW6BdT/j1/+0Zx3wY53YiMqbVWUYMk7dpThHQSZS/UxcSGg==,iv:Zie455aR5EdJcvP5wmQKcJuQ7wsTlMuEg5nuJgniMEU=,tag:Q2fl0WqtU3refRwwvyP9Mw==,type:str]
    routin-grok: ENC[AES256_GCM,data:PwyRFYAv86zqqcrlr8KqtCcMrgPdiG7X9e4RI5TVh+LLxOA=,iv:dzOQMPbaAFApaTtZNzzSCqh6IbUvLSkPEEiGoBhDy5I=,tag:z+nRs47zfRkOEKk4pK0tWQ==,type:str]
    routin-gpt-authorization: ENC[AES256_GCM,data:78f9uQd6c931DcIKcMplcguCL0MmgVaDtE5YRKi0U5cxnMMXMIZRANPC,iv:gp4BUNguWAl+jzc2JhF+Auf7einTMgvvReCCV025lac=,tag:DIaMT6vMvS2XseG/z7DKTA==,type:str]
    lucoo-grok: ENC[AES256_GCM,data:rYJq1PqiwA7ObN/ZjazlZAPEZO6M1xK/ppAJiNSUwag9iucezbl96AiTsAUc/NVzyo+S,iv:OD1iVuG6s8CeXEGK0p2ITbz3Uup4a9SpLBeAockA9gE=,tag:KUog874dUycb4oT+EakZUw==,type:str]
    lucoo-gemini-authorization: ENC[AES256_GCM,data:z6y+4CXelXsDXo7js2iGIq/vQHlvsfoq1sy2wPkCvTJrhrFYo8EttrJBbaLH5HebjIeD,iv:DQ58Et8vBFNDtgb+H0LwCVfug6RIzgocgScWAXerf2M=,tag:nJb1pswh7Ltfz/HY1G4+4g==,type:str]
    lucoo-gpt-authorization: ENC[AES256_GCM,data:NvoUd66JPX3NzYvPSLBWzEAuWtU3//ivBErbFDSh57n9BzkAGvlx82akCRIBbFO5KS1U,iv:cdbN8PcHCD72sY3+O3l0vpAor5ZaEkaLrnu0JedjYb4=,tag:qPxSPyOouh8o2hqau68p6g==,type:str]
    lucoo-claude: ENC[AES256_GCM,data:h8kFEN/3mSF50qGkZhtbOUaHN53X94uVLB6XyDKD9IdAcDh+tiITKqxrg6JlU0No8iaj,iv:SbzthR8oX9yCxCKFOKqZ9n238f/GkNYq7vtesv/i9mU=,tag:aS54GspQA2Sh6bxhmfrrHQ==,type:str]
    packy-grok: ENC[AES256_GCM,data:4ABgSQqV+HQNA24yADVXf1qLuZlGbNh+2NH31QnKThNuzsUIa8R86vqVMQTLPVfp01hQ,iv:1UglxpZGS9I6z/cVsyeuomHLljvrEHmDVBlHQy+8UGc=,tag:OcaRPl0wC/hUZkYNkGWj2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYODdkR3NJbkVRRVdNTHNV
            NHFGMys3MWMxRzBiRUxWV1VvQ29sbTd4S2drCkZGOTJ5ZElSMW9UWWE2OGhjQStI
            QzEzeHBJMGFSQkJNUlM3eSt0QS9Ga2MKLS0tIGlOTGFZVXFEVUtuSXMxRXFCRVh0
            MFJGZzBZUmtzWlRPM3dyZTdKdVlKYmsKchRDHnSEvA4GTkL7PpAJSUc80DRzyMLa
            Qoeal+x7b+Pq4VJGHqhlzeNaj3fcAxDuNfWs3W9VCgs+r9z7J97/Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c35qqyeuat7upert69arjelfjzkgfkwndddcze7tsyra7typlvpqp6j6vs
    lastmodified: "2026-08-07T07:42:55Z"
    mac: ENC[AES256_GCM,data:wYKwvWqV9Be1TPtqLu60AQrBzjD7HgGzpEcCRpSqUTpBqsYM6SIEmRctbIqKZKErMei1tYE1Q6l3hUVnyJtMsZHGUIvru9FowT4mJFspomTeJr8ImsvqDeyzS26zvrkL1KnPAyUr3lnilUUdRWSv5KlKWrlp5y0kslh9sfVAmiw=,iv:DPh9NcYFBrhE7g5rvvtxK/MQ2+YO2TT83NMva8GXGLA=,tag:kfX27bbMRbSjv7m3xyA5dQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
